apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-apps
  namespace: argo
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/bernardolsp/infraapps-projeto-final.git
      revision: feat/ultima_aula
      directories:
      - path: "*"
  template:
    metadata:
      name: '{{index .path.segments 0}}'
      annotations:
        # Use a conditional statement to determine the sync wave for a specific application
        argocd.argoproj.io/sync-wave: '{{if eq (index .path.segments 0) "crossplane-aws-resources"}}1{{else}}0{{end}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: "default"
      source:
        repoURL: https://github.com/bernardolsp/infraapps-projeto-final.git
        targetRevision: feat/ultima_aula
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index .path.segments 0}}'
      syncPolicy:
        automated: {}
        syncOptions:
        - CreateNamespace=true
        - Validate=false
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2