kind: ClusterSecretStore
apiVersion: external-secrets.io/v1beta1
metadata:
  name: aws-sm
  namespace: external-secrets
spec:
  provider:
    aws: 
      service: SecretsManager
      region: us-east-1