apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dev-eks-lab
  namespace: argo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-sm
    kind: ClusterSecretStore
  target:
    name: dev-eks-lab
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
  data:
    - secretKey: config
      remoteRef:
        key: argocd_cluster_dev_secret
        property: config
    - secretKey: name
      remoteRef:
        key: argocd_cluster_dev_secret
        property: name
    - secretKey: server
      remoteRef:
        key: argocd_cluster_dev_secret
        property: server
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: prod-eks-lab
  namespace: argo
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-sm
    kind: ClusterSecretStore
  target:
    name: prod-eks-lab
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
  data:
    - secretKey: config
      remoteRef:
        key: argocd_cluster_prod_secret
        property: config
    - secretKey: name
      remoteRef:
        key: argocd_cluster_prod_secret
        property: name
    - secretKey: server
      remoteRef:
        key: argocd_cluster_prod_secret
        property: server